package hrms.entity;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysEnumDataId generated by hbm2java
 */
@Embeddable
public class SysEnumDataId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private String tableName;
	private String columnName;
	private String enumType;
	private String enumValue;
	private String enumName;
	private Long sortId;
	private String dispName;
	private Byte status;
	private String remark;

	public SysEnumDataId() {
	}

	public SysEnumDataId(String tableName, String columnName, String enumType,
			String enumValue, String enumName, Long sortId, String dispName,
			Byte status, String remark) {
		this.tableName = tableName;
		this.columnName = columnName;
		this.enumType = enumType;
		this.enumValue = enumValue;
		this.enumName = enumName;
		this.sortId = sortId;
		this.dispName = dispName;
		this.status = status;
		this.remark = remark;
	}

	@Column(name = "TABLE_NAME", length = 20)
	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	@Column(name = "COLUMN_NAME", length = 20)
	public String getColumnName() {
		return this.columnName;
	}

	public void setColumnName(String columnName) {
		this.columnName = columnName;
	}

	@Column(name = "ENUM_TYPE")
	public String getEnumType() {
		return this.enumType;
	}

	public void setEnumType(String enumType) {
		this.enumType = enumType;
	}

	@Column(name = "ENUM_VALUE")
	public String getEnumValue() {
		return this.enumValue;
	}

	public void setEnumValue(String enumValue) {
		this.enumValue = enumValue;
	}

	@Column(name = "ENUM_NAME", length = 50)
	public String getEnumName() {
		return this.enumName;
	}

	public void setEnumName(String enumName) {
		this.enumName = enumName;
	}

	@Column(name = "SORT_ID")
	public Long getSortId() {
		return this.sortId;
	}

	public void setSortId(Long sortId) {
		this.sortId = sortId;
	}

	@Column(name = "DISP_NAME", length = 50)
	public String getDispName() {
		return this.dispName;
	}

	public void setDispName(String dispName) {
		this.dispName = dispName;
	}

	@Column(name = "STATUS")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Column(name = "REMARK", length = 50)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SysEnumDataId))
			return false;
		SysEnumDataId castOther = (SysEnumDataId) other;

		return ((this.getTableName() == castOther.getTableName()) || (this
				.getTableName() != null && castOther.getTableName() != null && this
				.getTableName().equals(castOther.getTableName())))
				&& ((this.getColumnName() == castOther.getColumnName()) || (this
						.getColumnName() != null
						&& castOther.getColumnName() != null && this
						.getColumnName().equals(castOther.getColumnName())))
				&& ((this.getEnumType() == castOther.getEnumType()) || (this
						.getEnumType() != null
						&& castOther.getEnumType() != null && this
						.getEnumType().equals(castOther.getEnumType())))
				&& ((this.getEnumValue() == castOther.getEnumValue()) || (this
						.getEnumValue() != null
						&& castOther.getEnumValue() != null && this
						.getEnumValue().equals(castOther.getEnumValue())))
				&& ((this.getEnumName() == castOther.getEnumName()) || (this
						.getEnumName() != null
						&& castOther.getEnumName() != null && this
						.getEnumName().equals(castOther.getEnumName())))
				&& ((this.getSortId() == castOther.getSortId()) || (this
						.getSortId() != null && castOther.getSortId() != null && this
						.getSortId().equals(castOther.getSortId())))
				&& ((this.getDispName() == castOther.getDispName()) || (this
						.getDispName() != null
						&& castOther.getDispName() != null && this
						.getDispName().equals(castOther.getDispName())))
				&& ((this.getStatus() == castOther.getStatus()) || (this
						.getStatus() != null && castOther.getStatus() != null && this
						.getStatus().equals(castOther.getStatus())))
				&& ((this.getRemark() == castOther.getRemark()) || (this
						.getRemark() != null && castOther.getRemark() != null && this
						.getRemark().equals(castOther.getRemark())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTableName() == null ? 0 : this.getTableName().hashCode());
		result = 37
				* result
				+ (getColumnName() == null ? 0 : this.getColumnName()
						.hashCode());
		result = 37 * result
				+ (getEnumType() == null ? 0 : this.getEnumType().hashCode());
		result = 37 * result
				+ (getEnumValue() == null ? 0 : this.getEnumValue().hashCode());
		result = 37 * result
				+ (getEnumName() == null ? 0 : this.getEnumName().hashCode());
		result = 37 * result
				+ (getSortId() == null ? 0 : this.getSortId().hashCode());
		result = 37 * result
				+ (getDispName() == null ? 0 : this.getDispName().hashCode());
		result = 37 * result
				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result
				+ (getRemark() == null ? 0 : this.getRemark().hashCode());
		return result;
	}

}
